// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZXXo2dFYUaVyu2Fz7zaHqpYoiQ6K4R60',
    appId: '1:786802683955:android:bef9cd305a878fe1f5b346',
    messagingSenderId: '786802683955',
    projectId: 'horus-e1151',
    databaseURL: 'https://horus-e1151-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'horus-e1151.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzqU0MUc8FOnMiEXuZW6F3PHtPGPi1044',
    appId: '1:786802683955:web:28aa61c074f03220f5b346',
    messagingSenderId: '786802683955',
    projectId: 'horus-e1151',
    authDomain: 'horus-e1151.firebaseapp.com',
    databaseURL: 'https://horus-e1151-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'horus-e1151.firebasestorage.app',
    measurementId: 'G-VX5SC9MJEC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH6ojZi-bDZ0_hylODsWd__hNhvvfw--I',
    appId: '1:786802683955:ios:00d49a645c133272f5b346',
    messagingSenderId: '786802683955',
    projectId: 'horus-e1151',
    databaseURL: 'https://horus-e1151-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'horus-e1151.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH6ojZi-bDZ0_hylODsWd__hNhvvfw--I',
    appId: '1:786802683955:ios:00d49a645c133272f5b346',
    messagingSenderId: '786802683955',
    projectId: 'horus-e1151',
    databaseURL: 'https://horus-e1151-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'horus-e1151.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzqU0MUc8FOnMiEXuZW6F3PHtPGPi1044',
    appId: '1:786802683955:web:d7091a1705376279f5b346',
    messagingSenderId: '786802683955',
    projectId: 'horus-e1151',
    authDomain: 'horus-e1151.firebaseapp.com',
    databaseURL: 'https://horus-e1151-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'horus-e1151.firebasestorage.app',
    measurementId: 'G-EVSELFMWM7',
  );

}